// examples/webdemo/src/components/midi-player/index.tsx
import { ChangeEvent, useEffect, useMemo, useRef, useState } from "react";
import { default as initMidiFileParser, midiToSimpleTracks, SimpleMidiEvent, SimpleMidiTrack } from "../../assets/midi-file-parser/midi_file_parser";
import useWasm from "../../hooks/useWasm";
import useEventBus from "../../hooks/useEventBus";
import { AudioGraph } from "../../audio-graph";
import BeatBarIndicator from "../beat-bar-indicator";
import ScheduleWorker from "./scheduleWorker?worker";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faFileImport, faPause, faPlay, faStop } from "@fortawesome/free-solid-svg-icons";
import MenuBarFaIcon from "../menu-bar-fa-icon";

// https://web.dev/articles/audio-scheduling
const intervalMillis = 25;
const intervalSeconds = intervalMillis / 1000;
const scheduleAheadTime = 0.1;

interface MidiPlayerProps {
    tempo: number,
    audioGraph: AudioGraph,
    midiFile: { name: string, data: Uint8Array } | undefined
}

function MidiPlayer({ tempo, audioGraph, midiFile }: MidiPlayerProps) {
    const [selectedMidiTrackIndex, setSelectedMidiTrackIndex] = useState<number>();
    const loadedMidiTracks = useMemo(() => {
        let midiTracks: SimpleMidiTrack[] = [];
        let error: string | null = null;

        if (!midiFile) {
            return { midiTracks, error };
        }

        try {
            midiTracks = midiToSimpleTracks(midiFile.data);
            if (midiTracks.length === 0) {
                error = "No midi tracks found"
            } else {
                setSelectedMidiTrackIndex(0);
            }
        }
        catch (ex) {
            error = ex as string;
        }

        return { midiTracks, error };
    }, [midiFile]);
    const selectedMidiTrack = useMemo(() => {
        if (!midiFile || loadedMidiTracks.error) {
            return null;
        }

        return loadedMidiTracks.midiTracks[selectedMidiTrackIndex!];
    }, [midiFile, loadedMidiTracks, selectedMidiTrackIndex]);

    const [playMidiStartTime, setPlayMidiStartTime] = useState<number | null>(null);
    const eventIterator = useRef<ArrayIterator<SimpleMidiEvent>>(null);
    const scheduledNotes = useRef<Set<number>>(new Set<number>());
    const [pausingTime, setPausingTime] = useState<number | null>(null);
    const nextEvent = useRef<SimpleMidiEvent>(null);
    const beatsPerSecond = useMemo(() => tempo / 60, [tempo]);
    const secondsPerBeat = useMemo(() => 60 / tempo, [tempo]);

    const scheduleWorker = useRef<Worker>(null);
    useEffect(() => {
        scheduleWorker.current = new ScheduleWorker();
        return () => scheduleWorker.current!.terminate();
    }, []);

    useEffect(() => {
        scheduleWorker.current!.onmessage = scheduleMidiEvents;
    }, [playMidiStartTime, pausingTime]);

    const [elapsedTimeInBeats, setElapsedTimeInBeats] = useState(0);
    const elapsedTimeInBeatsFloored = useMemo(() => Math.floor(elapsedTimeInBeats), [elapsedTimeInBeats]);
    const eventBus = useEventBus();

    const midiFileParserLoaded = useWasm(initMidiFileParser);

    const handleMidiTrackChange = (evt: ChangeEvent<HTMLSelectElement>) => {
        stopMidi();
        setSelectedMidiTrackIndex(parseInt(evt.target.value));
        eventIterator.current = null;
    }

    const startScheduler = () => scheduleWorker.current!.postMessage({ type: "start", interval: intervalMillis });

    const stopScheduler = () => scheduleWorker.current!.postMessage({ type: "stop" });

    const scheduleMidiEvents = () => {
        const elapsedSeconds = audioGraph.currentTime - playMidiStartTime!;
        const elapsedBeats = elapsedSeconds * beatsPerSecond;
        setElapsedTimeInBeats(current => current + intervalSeconds * beatsPerSecond);

        while (nextEvent.current !== null && nextEvent.current.time < audioGraph.currentTime + scheduleAheadTime) {
            if (pausingTime === null || nextEvent.current.type === "off") {
                const { time, key, velocity } = nextEvent.current;
                const type = nextEvent.current.type === "on" ? "noteScheduleOn" : "noteScheduleOff";
                eventBus.publish(type, { time, key, velocity });
            }

            if (nextEvent.current.type === "on") {
                scheduledNotes.current.add(nextEvent.current.key);
            } else {
                scheduledNotes.current.delete(nextEvent.current.key);
                if (pausingTime !== null && scheduledNotes.current.size === 0) {
                    setPlayMidiStartTime(null);
                    stopScheduler();
                    setPausingTime(null);
                    const remainingEvents = [...eventIterator.current!].map(event => {
                        return { ...event, time: event.time - elapsedBeats };
                    });
                    eventIterator.current = remainingEvents[Symbol.iterator]();
                    break;
                }
            }

            if (!advanceNextEvent()) {
                setPlayMidiStartTime(null);
                stopScheduler();
                eventIterator.current = null;
                break;
            }
        }
    };

    const advanceNextEvent = () => {
        const { value, done } = eventIterator.current!.next();
        if (done) {
            return false;
        }

        nextEvent.current = { ...value, time: value.time * secondsPerBeat + playMidiStartTime! };
        return true;
    };

    const playMidi = () => {
        if (eventIterator.current === null) {
            setElapsedTimeInBeats(0);
            eventIterator.current = selectedMidiTrack!.events![Symbol.iterator]();
        }

        if (!advanceNextEvent()) {
            return;
        }

        setPlayMidiStartTime(audioGraph.currentTime);
        startScheduler();

        eventBus.publish("hostStartPlaying", undefined);
    }

    const pauseMidi = () => {
        setPausingTime(audioGraph.currentTime);
        eventBus.publish("hostStopPlaying", undefined);
    }

    const stopMidi = () => {
        setPlayMidiStartTime(null);
        stopScheduler();

        scheduledNotes.current.forEach(note => {
            eventBus.publish("noteScheduleOff", { time: audioGraph.currentTime, key: note, velocity: 0 });
        });
        scheduledNotes.current.clear();

        setElapsedTimeInBeats(0);
        eventIterator.current = null;
        eventBus.publish("hostStopPlaying", undefined);
    }

    if (!midiFileParserLoaded) {
        return null;
    }

    return (
        <>
            <div className="menu-bar-group-item">
                <MenuBarFaIcon icon={faFileImport} label="midi" />
                {
                    midiFile
                        ? loadedMidiTracks.error
                            ? `Failed to load ${midiFile.name}: ${loadedMidiTracks.error}`
                            : midiFile.name
                        : "none"
                }
            </div>
            {
                !midiFile || loadedMidiTracks.error
                    ? null
                    : <div className="menu-bar-group-item">
                        <select onChange={handleMidiTrackChange}>
                            {
                                loadedMidiTracks.midiTracks.map((track, index) => {
                                    const timeSignature = track.timeSignature ? track.timeSignature.numerator + "/" + track.timeSignature.denominator : null;
                                    let trackLabel = `Track ${index}: ${track.beats} beats`;
                                    if (timeSignature)
                                        trackLabel += `, ${timeSignature}`;
                                    return <option key={index} value={index}>{trackLabel}</option>;
                                })
                            }
                        </select>
                    </div>
            }
            {
                !selectedMidiTrack || !selectedMidiTrack.timeSignature
                    ? null
                    : <div className="menu-bar-group-item">
                        <BeatBarIndicator currentBeat={elapsedTimeInBeatsFloored % selectedMidiTrack.timeSignature.numerator}
                            beatsPerBar={selectedMidiTrack.timeSignature.numerator} />
                    </div>
            }
            <div className="menu-bar-group-item">
                {playMidiStartTime === null
                    ? <button onClick={playMidi} disabled={selectedMidiTrack === null}><FontAwesomeIcon icon={faPlay} /></button>
                    : <button onClick={pauseMidi} disabled={selectedMidiTrack === null}><FontAwesomeIcon icon={faPause} /></button>
                }
                <button onClick={stopMidi} disabled={selectedMidiTrack === null}><FontAwesomeIcon icon={faStop} /></button>
            </div>
            <div className="menu-bar-group-item">
                {elapsedTimeInBeatsFloored + 1}
            </div>
        </>
    )
}

export default MidiPlayer;

// examples/webdemo-solid/src/components/midi-player/index.tsx
import { createEffect, createSignal, For, onCleanup, onMount, Show, type JSX } from "solid-js";
import { default as initMidiFileParser, midiToSimpleTracks, type SimpleMidiEvent, type SimpleMidiTrack } from "../../assets/midi-file-parser/midi_file_parser";
import type AudioGraph from "../../audio-graph";
import ScheduleWorker from "./scheduleWorker?worker";
import type { EventBus } from "../../event-bus";
import BeatBarIndicator from "../beat-bar-indicator";
import { faFileImport } from "@fortawesome/free-solid-svg-icons/faFileImport";
import MenuBarFaIcon from "../menu-bar-fa-icon";
import FaIcon from "../fa-icon";
import { faPause, faPlay, faStop } from "@fortawesome/free-solid-svg-icons";

// https://web.dev/articles/audio-scheduling
const intervalMillis = 25;
const intervalSeconds = intervalMillis / 1000;
const scheduleAheadTime = 0.1;

type MidiPlayerProps = {
    tempo: number,
    audioGraph: AudioGraph,
    eventBus: EventBus,
    midiFile: { name: string, data: Uint8Array } | undefined
};

// In Solid, reactive properties shouldn't be destructured yet in the function signature
function MidiPlayer(props: MidiPlayerProps) {
    const [selectedMidiTrackIndex, setSelectedMidiTrackIndex] = createSignal<number>();
    const [loadedMidiTracks, setLoadedMidiTracks] = createSignal<{ midiTracks: SimpleMidiTrack[], error: string | null }>({ midiTracks: [], error: null });
    const selectedMidiTrack = () => {
        if (!props.midiFile || loadedMidiTracks().error) {
            return null;
        }

        return loadedMidiTracks().midiTracks[selectedMidiTrackIndex()!];
    };
    const [playMidiStartTime, setPlayMidiStartTime] = createSignal(0);
    const [pausingTime, setPausingTime] = createSignal<number>();
    const beatsPerSecond = () => props.tempo / 60;
    const secondsPerBeat = () => 60 / props.tempo;
    const [elapsedTimeInBeats, setElapsedTimeInBeats] = createSignal(0);
    const elapsedTimeInBeatsFloored = () => Math.floor(elapsedTimeInBeats());
    const [midiFileParserLoaded, setMidiFileParserLoaded] = createSignal(false);

    let eventIterator: ArrayIterator<SimpleMidiEvent> | undefined;
    let scheduledNotes = new Set<number>();
    let nextEvent: SimpleMidiEvent | undefined;
    let scheduleWorker: Worker | undefined;
    
    onMount(async () => {
        await initMidiFileParser();
        setMidiFileParserLoaded(true);
        scheduleWorker = new ScheduleWorker();
        scheduleWorker.onmessage = scheduleMidiEvents;
    });

    onCleanup(() => {
        scheduleWorker!.terminate();
    });
    
    createEffect(() => {
        let midiTracks: SimpleMidiTrack[] = [];
        let error: string | null = null;

        if (props.midiFile) {
            try {
                midiTracks = midiToSimpleTracks(props.midiFile.data);
                if (midiTracks.length === 0) {
                    error = "No midi tracks found"
                } else {
                    setSelectedMidiTrackIndex(0);
                }
            }
            catch (ex) {
                error = ex as string;
            }
        }

        setLoadedMidiTracks({ midiTracks, error });
    });

    const handleMidiTrackChange: JSX.EventHandler<HTMLSelectElement, Event> = evt => {
        stopMidi();
        setSelectedMidiTrackIndex(parseInt(evt.currentTarget.value));
        eventIterator = undefined;
    };

    const startScheduler = () => scheduleWorker!.postMessage({ type: "start", interval: intervalMillis });

    const stopScheduler = () => scheduleWorker!.postMessage({ type: "stop" });

    const scheduleMidiEvents = () => {
        const elapsedSeconds = props.audioGraph.currentTime - playMidiStartTime();
        const bps = beatsPerSecond();
        const elapsedBeats = elapsedSeconds * bps;
        setElapsedTimeInBeats(current => current + intervalSeconds * bps);

        while (nextEvent !== undefined && nextEvent.time < props.audioGraph.currentTime + scheduleAheadTime) {
            if (pausingTime() === undefined || nextEvent.type === "off") {
                const { time, key, velocity } = nextEvent;
                const type = nextEvent.type === "on" ? "noteScheduleOn" : "noteScheduleOff";
                props.eventBus.publish(type, { time, key, velocity });
            }

            if (nextEvent.type === "on") {
                scheduledNotes.add(nextEvent.key);
            } else {
                scheduledNotes.delete(nextEvent.key);
                if (pausingTime() !== undefined && scheduledNotes.size === 0) {
                    setPlayMidiStartTime(0);
                    stopScheduler();
                    setPausingTime(undefined);
                    const remainingEvents = [...eventIterator!].map(event => {
                        return { ...event, time: event.time - elapsedBeats };
                    });
                    eventIterator = remainingEvents[Symbol.iterator]();
                    break;
                }
            }

            if (!advanceNextEvent()) {
                setPlayMidiStartTime(0);
                stopScheduler();
                eventIterator = undefined;
                break;
            }
        }
    };

    const advanceNextEvent = () => {
        const { value, done } = eventIterator!.next();
        if (done) {
            return false;
        }

        nextEvent = { ...value, time: value.time * secondsPerBeat() + playMidiStartTime() };
        return true;
    };

    const playMidi = () => {
        if (eventIterator === undefined) {
            setElapsedTimeInBeats(0);
            eventIterator = selectedMidiTrack()!.events![Symbol.iterator]();
        }

        if (!advanceNextEvent()) {
            return;
        }

        setPlayMidiStartTime(props.audioGraph.currentTime);
        startScheduler();

        props.eventBus.publish("hostStartPlaying", undefined);
    }

    const pauseMidi = () => {
        setPausingTime(props.audioGraph.currentTime);
        props.eventBus.publish("hostStopPlaying", undefined);
    }

    const stopMidi = () => {
        setPlayMidiStartTime(0);
        stopScheduler();

        scheduledNotes.forEach(note => {
            props.eventBus.publish("noteScheduleOff", { time: props.audioGraph.currentTime, key: note, velocity: 0 });
        });
        scheduledNotes.clear();

        setElapsedTimeInBeats(0);
        eventIterator = undefined;
        props.eventBus.publish("hostStopPlaying", undefined);
    }

    return (
        <Show when={midiFileParserLoaded()}>
            <div class="menu-bar-group-item">
                <MenuBarFaIcon definition={faFileImport} label="midi" />
                {
                    props.midiFile
                        ? loadedMidiTracks().error
                            ? `Failed to load ${props.midiFile.name}: ${loadedMidiTracks().error}`
                            : props.midiFile.name
                        : "none"
                }
            </div>
            <Show when={props.midiFile && !loadedMidiTracks().error}>
                <div class="menu-bar-group-item">
                    <select onChange={handleMidiTrackChange}>
                        <For each={loadedMidiTracks().midiTracks}>{(track, index) => {
                            const timeSignature = track.timeSignature ? track.timeSignature.numerator + "/" + track.timeSignature.denominator : null;
                            let trackLabel = `Track ${index()}: ${track.beats} beats`;
                            if (timeSignature)
                                trackLabel += `, ${timeSignature}`;
                            return <option value={index()}>{trackLabel}</option>;
                        }}</For>
                    </select>
                </div>
            </Show>
            <Show when={selectedMidiTrack()?.timeSignature}>
                <div class="menu-bar-group-item">
                    <BeatBarIndicator currentBeat={elapsedTimeInBeatsFloored() % selectedMidiTrack()!.timeSignature!.numerator}
                        beatsPerBar={selectedMidiTrack()!.timeSignature!.numerator} />
                </div>
            </Show>
            <div class="menu-bar-group-item">
                {playMidiStartTime() === 0
                    ? <button onClick={playMidi} disabled={selectedMidiTrack() === null}><FaIcon definition={faPlay} /></button>
                    : <button onClick={pauseMidi} disabled={selectedMidiTrack() === null}><FaIcon definition={faPause} /></button>
                }
                <button onClick={stopMidi} disabled={selectedMidiTrack() === null}><FaIcon definition={faStop} /></button>
            </div>
            <div class="menu-bar-group-item">
                {elapsedTimeInBeatsFloored() + 1}
            </div>
        </Show>
    )
}

export default MidiPlayer;
